name: peanut
version: 1.1.0-dev
description: pub build to gh-pages
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/peanut.dart
environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  args: '>=0.13.0 <2.0.0'
  git: ^0.4.3
  io: ^0.3.2+1
  path: ^1.3.4

dev_dependencies:
  build_runner: ^0.7.10
  build_web_compilers: ^0.3.0

executables:
  peanut: peanut
